name: offset_list
description: A list with an offset for accessing elements. This is useful for correctly implementing mathematical formulas that assume a different starting index than 0.
version: 0.1.0
repository: https://github.com/mcmah309/offset_list

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
